# Generated by Django 3.0.6 on 2020-05-25 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, max_length=254, verbose_name='Email Address')),
                ('age', models.IntegerField(default=0, verbose_name='Age on months')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patient',
                'db_table': 'patient',
            },
        ),
    ]
