# Generated by Django 3.0.6 on 2020-05-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_remove_patient_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
    ]
