# Generated by Django 3.0.6 on 2020-05-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20200528_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
    ]
